services:
  radicle:
    image: ghcr.io/ozeliurs/radicle-seed-docker/radicle:latest
    container_name: radicle
    restart: unless-stopped
    environment:
      - RAD_ALIAS=seed.ozeliurs.com
    volumes:
      - ./heartwood:/root/
    ports:
      - 8776:8776
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.simple-service.rule=Host(`seed.${BASE_DOMAIN:-ozeliurs.com}`)"
      - "traefik.http.routers.simple-service.entrypoints=websecure"
      - "traefik.http.routers.simple-service.tls=true"
      - "traefik.http.routers.simple-service.tls.certresolver=cloudflare"
      - "traefik.http.services.simple-service.loadbalancer.server.port=8080"

networks:
  traefik:
    external: true